# Generated by Django 4.1.5 on 2023-03-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos_web/static/media'),
        ),
    ]
