# Generated by Django 3.2.18 on 2023-04-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0003_printsize_surfacetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintSize',
        ),
        migrations.DeleteModel(
            name='SurfaceType',
        ),
    ]
