# Generated by Django 4.1.5 on 2023-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0003_alter_photo_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
