# Generated by Django 4.1.5 on 2023-03-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0004_photo_datetime_photo_make_photo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='make',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='model',
        ),
        migrations.CreateModel(
            name='MetaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='photos_web.photo')),
            ],
        ),
    ]
