# Generated by Django 4.1.5 on 2023-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0006_remove_metaphoto_model_metaphoto_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaphoto',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metaphoto',
            name='orientation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metaphoto',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
