# Generated by Django 4.1.5 on 2023-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0007_metaphoto_height_metaphoto_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
