# Generated by Django 4.1.5 on 2023-03-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0008_photo_exif_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='exif_data',
        ),
    ]
