# Generated by Django 4.1.5 on 2023-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0009_remove_photo_exif_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
