# Generated by Django 4.1.5 on 2023-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0010_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
