# Generated by Django 4.1.5 on 2023-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0011_photo_device_photo_orientation_photo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='meta_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
