# Generated by Django 4.1.5 on 2023-03-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0012_photo_gps_coordinates_photo_height_photo_meta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='meta_data2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
