# Generated by Django 4.1.5 on 2023-03-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0013_photo_meta_data2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='meta_data2',
        ),
    ]
