# Generated by Django 4.1.5 on 2023-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0015_photo_bands_photo_brightness_photo_image_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/webp'),
        ),
    ]
