# Generated by Django 4.1.5 on 2023-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0016_photo_webp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_web/static/media/webp'),
        ),
    ]
