# Generated by Django 4.1.5 on 2023-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0019_alter_photo_webp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos_web/static/media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_web/static/media'),
        ),
    ]
