# Generated by Django 4.1.5 on 2023-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0020_photo_file_name_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='png_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_web/static/media'),
        ),
    ]
