# Generated by Django 4.1.5 on 2023-03-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0021_photo_png_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='png_image',
        ),
    ]
