# Generated by Django 4.1.5 on 2023-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0022_remove_photo_png_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='png_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_web/static/photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos_web/static/photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_web/static/photos'),
        ),
    ]
