# Generated by Django 4.1.5 on 2023-03-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0023_photo_png_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='webp_image',
        ),
    ]
