# Generated by Django 4.1.5 on 2023-03-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0024_remove_photo_webp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
    ]
