# Generated by Django 4.1.5 on 2023-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0025_remove_photo_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='png_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
