# Generated by Django 4.1.5 on 2023-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0030_photo_created_at_photo_likes_photo_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='likes',
            new_name='user_likes',
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
