# Generated by Django 4.1.5 on 2023-03-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_web', '0031_rename_likes_photo_user_likes_alter_photo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
