# Generated by Django 4.1.5 on 2023-03-28 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos_web', '0033_alter_photo_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
