# Generated by Django 3.2.18 on 2023-04-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20230419_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.option')),
            ],
        ),
    ]
