# Generated by Django 3.2.18 on 2023-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_delete_sizeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
