# Generated by Django 3.2.18 on 2023-04-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_product_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('100x200', '100x200'), ('200x300', '200x300')], max_length=10)),
                ('print_type', models.CharField(choices=[('Frame', 'Frame'), ('Print', 'Print')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='catalogue.product')),
            ],
            options={
                'unique_together': {('product', 'size', 'print_type')},
            },
        ),
    ]
