"""
Django settings for lukas_mandik_photos project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
# after import os
from oscar.defaults import *
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ei&1mf4l=t+ioj24gzd&&ch1&dz#h4h)qhs6v)o!ejt@2zdi4x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "lvh.me"]

LOGIN_REDIRECT_URL = '/'

LIKED_PHOTOS_COOKIE_MAX_AGE = 31536000

USE_TZ = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_countries',

    'photos_web',
    'livereload',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'oscar',
    'oscar.apps.analytics',
    'oscar.apps.checkout',
    'oscar.apps.address',
    'oscar.apps.shipping',
    # 'oscar.apps.catalogue',
    'lukas_mandik_photos.catalogue.apps.CatalogueConfig',
    'oscar.apps.catalogue.reviews',
    'oscar.apps.partner',
    'oscar.apps.basket',
    'oscar.apps.payment',
    'oscar.apps.offer',
    'oscar.apps.order',
    'oscar.apps.customer',
    'oscar.apps.search',
    'oscar.apps.voucher',
    'oscar.apps.wishlists',
    'oscar.apps.communication',
    'oscar.apps.dashboard',
    'oscar.apps.dashboard.reports',
    'oscar.apps.dashboard.users',
    'oscar.apps.dashboard.orders',
    'oscar.apps.dashboard.catalogue',
    'oscar.apps.dashboard.offers',
    'oscar.apps.dashboard.partners',
    'oscar.apps.dashboard.pages',
    'oscar.apps.dashboard.ranges',
    'oscar.apps.dashboard.reviews',
    'oscar.apps.dashboard.vouchers',
    'oscar.apps.dashboard.communications',
    'oscar.apps.dashboard.shipping',
    # 3rd-party apps that oscar depends on
    'widget_tweaks',
    'haystack',
    'treebeard',
    'sorl.thumbnail',
    'django_tables2',
]

SITE_ID = 2

SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'oscar.apps.basket.middleware.BasketMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'lukas_mandik_photos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'django.template.context_processors.request',
                # oscars context processors
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.apps.communication.notifications.context_processors.notifications',
                'oscar.core.context_processors.metadata',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

    'oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',

]
WSGI_APPLICATION = 'lukas_mandik_photos.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lukasmandik',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/images/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_ROOT = BASE_DIR / 'static/images'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

EXIFTOOL_PATH = '/usr/local/bin/exiftool'  # cesta k exiftoolu na vašom počítači

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pre Django Allauth

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access type': "online"
        }
    }
}
LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'  # Zmeňte toto na URL, na ktorú chcete presmerovať používateľov po prihlásení
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Nastavte toto na 'none', ak nechcete overenie e-mailu

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
ACCOUNT_USER_DISPLAY = lambda user: user.get_full_name()
# ACCOUNT_ADAPTER = 'lukas_mandik_photos.allauth_adapter.CustomAccountAdapter'



ACCOUNT_FORMS = {
    'signup': 'photos_web.forms.MyCustomSignupForm',
}


# ACCOUNT_SIGNUP_FORM_CLASS = 'photos_web.forms.CustomSignupForm'


# OSCAR_REQUIRED_ADDRESS_FIELDS = (
#     'first_name', 'last_name', 'line1', 'line4', 'postcode', 'country'
# )
# OSCAR_DYNAMIC_CLASS_LOADER = 'oscar.core.loading.default_class_loader'
# OSCAR_DEFAULT_CURRENCY = 'USD'
# OSCAR_SLUG_FUNCTION = 'oscar.core.utils.default_slugifier'
# OSCAR_SLUG_MAP = ()
# OSCAR_SLUG_BLACKLIST = ()
# OSCAR_SLUG_ALLOW_UNICODE = True
# OSCAR_ALLOW_ANON_CHECKOUT = False
# OSCAR_EAGER_ALERTS = False
# OSCAR_DELETE_IMAGE_FILES = True
# OSCAR_PRODUCTS_PER_PAGE = 20  # Alebo akúkoľvek inú hodnotu, ktorú chcete nastaviť
# OSCAR_OFFERS_PER_PAGE = 20  # Alebo akúkoľvek inú hodnotu, ktorú chcete nastaviť
# OSCAR_REVIEWS_PER_PAGE = 10  # Alebo akúkoľvek inú hodnotu, ktorú chcete nastaviť
# OSCAR_RECENTLY_VIEWED_COOKIE_NAME = 'recently_viewed_products'  # Alebo akýkoľvek iný názov cookie, ktorý chcete použiť
# OSCAR_RECENTLY_VIEWED_COOKIE_LIFETIME = 1209600
# OSCAR_RECENTLY_VIEWED_COOKIE_SECURE = False  # Alebo True, ak chcete, aby sa cookie odosielali iba cez HTTPS
# OSCAR_RECENTLY_VIEWED_PRODUCTS = 20
# OSCAR_SEARCH_FACETS = {
#     'fields': {
#         # ...
#     },
#     'queries': {},
# }
# OSCAR_SLUG_MAP = {}  # prípadne prispôsobte hodnoty podľa potreby
# OSCAR_SLUG_BLACKLIST = {}  # prípadne prispôsobte hodnoty podľa potreby


HAYSTACK_CONNECTIONS = {
   'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
   },
}
COUNTRY_CODE = 'SK'
CURRENCY_CODE = 'EUR'

COUNTRIES_FIRST = True






